### ISSUE TITLE
Run out of memory in GAP master branch

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/matgrp#12]
This is new after recent changes in the GAP master branch:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/641220759
```
########> Diff in /home/gap/inst/gap-master/pkg/matgrp/tst/basic.tst:23
# Input is:
cl:=ConjugacyClasses(g);;
# Expected output:
# But found:
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
```
It used to work before.

**Comment by olexandr-konovalov** [comment]
@hulpke ping to trigger notification, in case you haven't seen this yet.

**Comment by hulpke** [comment]
Thank you -- will be another library fix.
