### ISSUE TITLE
Add standard tests

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/matgrp#4]
There is no `TestFile` component in the `PackageInfo.g` file. It is recommended to specify a short test (to run for no more than several minutes) which may be used to check that a package works as expected. For deposited packages, these tests are run regularly as a part of the standard GAP test suite. Please see (in GAP 4.9.0 or GAP development version) `?TestPackage`, `?Tests files for a GAP package` and also `?TestDirectory` for more information.

**Comment by hulpke** [comment]
Given the functionality (which is based of recog, which is probabilistic), as well as the kind of calculations done, it is hard to construct a meaningful test that only runs a few minutes.
If it can be 5-10 minutes, I'll do so.

**Comment by olexandr-konovalov** [comment]
5 would be Ok for default tests (i.e. specified in `PackageInfo.g`). Longer tests are also OK - you can run a test for up to ~50 minutes in Travis CI, and configuring it for your package you can ensure that each commit/pull request is tested.

**Comment by hulpke** [comment]
There now is a tst directory with a smallish calculation (conjugacy classes in a matrix group over Z/(3^3*89)   )
